# Generated by Django 4.0.2 on 2022-02-25 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showroom', '0002_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicles',
            options={'ordering': ['posting_date']},
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='likes',
        ),
        migrations.AddField(
            model_name='seller',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='seller',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
