# Generated by Django 4.0.4 on 2022-05-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_alter_vehicles_options_remove_vehicles_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='whatsapp_contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
