# Generated by Django 4.0.4 on 2022-07-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0004_alter_seller_whatsapp_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chattext',
            name='chat',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatText',
        ),
    ]
